name: chrome
version: 0.9.0
authors:
- Devon Carew <devoncarew@gmail.com>
- Adam Singer <financeCoding@gmail.com>
- Kevin Moore <kevin@thinkpixellab.com>
description: A library for accessing the Chrome APIs in a packaged app or extension.
homepage: https://github.com/dart-gde/chrome.dart
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  barback: any
dev_dependencies:
  args: any
  browser: any
  logging: any
  mockito: any
  parsers: '>=0.14.0 <0.15.0'
  path: any
  test: ^0.12.0
  unscripted: ^0.6.0
transformers:
- chrome
- $dart2js:
   csp: true
